// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GunBoundSpriteKit",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "GunBoundSpriteKit",
            targets: ["AppModule"],
            bundleIdentifier: "org.pureswift.GunBoundSpriteKit",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .star),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    dependencies: [
        .package(path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "GunBound", package: "GunBound"),
                .product(name: "GunBoundProtocol", package: "GunBound"),
                .product(name: "GunBoundFile", package: "GunBound"),
                .product(name: "GunBoundClient", package: "GunBound")
            ],
            path: "AppModule"
        )
    ]
)