// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GunBoundSpriteKit",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "GunBoundSpriteKit",
            targets: ["AppModule"],
            bundleIdentifier: "org.pureswift.Gtest1",
            teamIdentifier: "E795R2E2E8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/PureSwift/Socket", "0.5.2"..<"1.0.0"),
        .package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", "1.6.0"..<"2.0.0"),
        .package(url: "https://github.com/apple/swift-argument-parser", "1.2.0"..<"2.0.0")
    ],
    targets: [
        .target(
            name: "BinaryParsing",
            path: "BinaryParsing",
            swiftSettings: [
                .enableExperimentalFeature("Lifetimes")
            ]
        ),
        .target(
            name: "GunBoundProtocol",
            dependencies: [
                "BinaryParsing"
            ],
            path: "GunBoundProtocol"
        ),
        .target(
            name: "GunBoundFile",
            dependencies: [
                "BinaryParsing"
            ],
            path: "GunBoundFile"
        ),
        .target(
            name: "GunBound",
            dependencies: [
                "GunBoundProtocol",
                .product(name: "Socket", package: "Socket"),
                .product(name: "CryptoSwift", package: "CryptoSwift"),
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ],
            path: "GunBound",
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        ),
        .target(
            name: "GunBoundClient",
            dependencies: [
                "GunBound",
                "GunBoundProtocol",
                "GunBoundFile"
            ],
            path: "GunBoundClient",
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        ),
        .executableTarget(
            name: "AppModule",
            dependencies: [
                "GunBound",
                "GunBoundProtocol",
                "GunBoundFile",
                "GunBoundClient"
            ],
            path: "AppModule",
            resources: [
                .copy("Resources")
            ],
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        )
    ]
)