name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-15
    strategy:
      matrix:
        config: ["debug", "release"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -c ${{ matrix.config }}
    - name: Test
      run: swift test -c ${{ matrix.config }}